spring.application.name=test
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot
spring.datasource.username=postgres
spring.datasource.password=Navaneethveer
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size = 200KB


spring.security.user.name = veer
spring.security.user.password = veer