spring.application.name=test

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

#spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.client-type=jedis

spring.ai.vectorstore.type=redis

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.6-flash
spring.ai.google.genai.embedding.project-id=${GEMINI_PROJECT_ID}

spring.ai.google.genai.embedding.api-key = ${GEMINI_API_KEY}
spring.ai.google.genai.embedding.project-id = ${GEMINI_PROJECT_ID}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-2


spring.ai.chat.memory.repository.jdbc.initialize-schema=always


spring.ai.vectorstore.redis.initialize-schema = true


razorpay.api.key = ${RAZORPAY_API_KEY}
razorpay.api.secret = ${RAZORPAY_API_SECRETS}
